### ISSUE TITLE
Weird Base64 Behavior on Session Management 1

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#220]
Session management challenge one displayed some WEIRD behaviour in how it strips == from submited cookies. I wana look into it and make sure we're not broken here

**Comment by markdenihan** [comment]
There is no flaw here with shepherd! Closing

**Comment by Shruti-s-kulkarni** [comment]
I am doing Shepherd challenges. On Session Management Challenge One, the result does not work. I have tried changing the value of checksum from dXNlclJvbGU9dXNlcg== to dXNlclJvbGU9YWRtaW4=, but the solution is not accepted. Please can you help?

**Comment by ThomasPonnet** [comment]
Similar to the last poster I got as far as changing the checksum in the header. What actually happens, is that the 'Hack detected' message is no longer displayed. Instead a new GET message is sent off resulting in a 405 Method Not Allowed error. So progress but no success.
Because of that I also tried the following:
- Several permutations of changing the the three body values to true (set to false by default) with and without the changed checksum (I assume the checksum has to be changed though). 
- Also using dXNlclJvbGU9YWRtaW5pc3RyYXRvcg== doesn't help. 
- Same with adding user | admin in the body.
- Same with removing all three values
If you have any hints (either direct or here) where I'm going wrong I'd be grateful :-)
And thank you for providing this great tool to teach about web security.

**Comment by markdenihan** [comment]
@Shruti-s-kulkarni - That is not the correct user role. That is not a bug

@ThomasPonnet - That is not a bug. That sounds like it should be a POST Request

This is not the forum for tips on how to solve levels, or on techniques to complete levels.

**Comment by ThomasPonnet** [comment]
@markdenihan Thanks for your comment, I updated my last post to remove the hint. I tried that but no luck, yet, but at least I know roughly where to look. I'm new here so apologies for posting in the wrong place. The sourceforge forums seems pretty dead - I assume people head to stackexchange or reddit? Ta for your help
