### ISSUE TITLE
More realistic force browing

### ISSUE THREAD

**Issue by vanderaj** [OWASP/SecurityShepherd#269]
The admin functionality lesson is trivial to perform, but it is not realistic. I would expect that this lesson be done using content discovery or fuzzing using directory lists or Dir Buster rather than provide a direct link in the lesson page. 

I would also like the admin page to be more like an admin login page than blank, as that's usually what I see if I do it in real life.

**Comment by SeanDuggan** [comment]
Thanks for the feedback vanderaj. 

I'm closing this request as Security Shepherd is aimed at a wide variety of users, from noobs to pros and we have to cater to them all. I agree that it's trivial, but as for realistic, I've encountered this sort of issue in the wild, in many forms. By providing the link in the source code as a hidden div, the lesson encourages players (who could be new to pen testing) to manually find the link, rather than rely on tools. 

As for the blank page, that's a nasty trick to make players second guess themselves. Curious players will inspect the page source (or scroll down if they see the scrollbar.)
