### ISSUE TITLE
Issue loading CSS on Setup Page

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#345]
![image](https://user-images.githubusercontent.com/912403/42769110-33b8d6a6-8919-11e8-827a-e8421849f9c6.png)

**Comment by markdenihan** [comment]
Replying to comments via email doesn't work any more apparently!

I had said via mail: Paul, can you check if that occurs when the project is not deployed as ROOT? I don't get that issue and that's the only difference I have to your setup atm

Reproduced this locally because it working was actually a cached copy of the CSS

@gbena I suspect this is a mass redirect that is in place when the db props are not detected? Can you white-list the css folder?

**Comment by gbena** [comment]
This PR https://github.com/OWASP/SecurityShepherd/pull/350 should nail it.
