### ISSUE TITLE
Migrate to GHA from TravisCI

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#574]

**Comment by ismisepaul** [comment]
The problem here is that Shepherd changed from a [properties file ](https://github.com/OWASP/SecurityShepherd/blob/d5c716629a9ff66b9dce2360e7b11a0c34bc9674/src/test/resources/conf/database.properties#L1)for running tests to [hardcoding](https://github.com/OWASP/SecurityShepherd/blob/28740a51419a0ef9ef7b38a52b2f54212f69a0e2/src/test/java/testUtils/TestProperties.java#L404) 

So when it runs in gitlab actions the port has changed from 3306 to 8888. Then if that's adjusted there's a problem with the various users connecting as the address is not localhost/127.0.0.1 but an IP of a docker container so you get errors like

```
ERROR  @ 21 Dec 15:59:01,564 [main] (Setter.java:351) - CsrfChallenge4 TokenUpdate Failure: java.sql.SQLException: Access denied for user 'csrfChalFour'@'172.18.0.1' (using password: YES)
Tests run: 53, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 26.576 sec <<< FAILURE! - in dbProcs.SetterTest
testSetCsrfChallengeSevenCsrfToken(dbProcs.SetterTest)  Time elapsed: 1.117 sec  <<< FAILURE!
java.lang.AssertionError: Could not Set CSRF Chalenge 7 Token
	at dbProcs.SetterTest.testSetCsrfChallengeSevenCsrfToken(SetterTest.java:293)
```

I think the values for testing e.g. hostname, username, password should be dynamic and not hardcoded. 

So grab the IP of the mysql server in docker with
```docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <image-name>```

or else create the schemas in the db and apply grants like 

```
GRANT ALL PRIVILEGES ON CsrfChallenge4.* TO 'csrfChalFour'@'%';
GRANT ALL PRIVILEGES ON csrfChallengeEnumTokens.* TO 'csrfChalEnuer'@'%';
GRANT ALL PRIVILEGES ON SqlInjLesson.* TO 'firstBloodyMessL'@'%';
```

But I'm leaning towards making things dynamic somehow, but I'm not sure of the best approach...
