### ISSUE TITLE
[BUG] Docker compose: mysql is not accessible

### ISSUE THREAD

**Issue by ymartin59** [OWASP/SecurityShepherd#587]
When running with "docker-compose up" according to instructions, setup page requests for database connection.

In tomcat log, I can observe:
```
secshep_tomcat |  INFO  @ 28 Oct 12:00:20,777 [https-openssl-nio-8443-exec-4] (Setup.java:357) - isInstalled got SQL exception java.sql.SQLException: null,  message from server: "Host '172.19.0.4' is not allowed to connect to this MySQL server", assuming not installed.
```

This probably comes from mysql startup failure according to logs:

```
secshep_mysql | 2021-10-28T09:39:20.010994Z 0 [Note] mysqld (mysqld 5.7.26) starting as process 1 ...
[...]
secshep_mysql | 2021-10-28T09:39:20.251996Z 0 [Note] InnoDB: Buffer pool(s) load completed at 211028  9:39:20                                                  
secshep_mysql | 2021-10-28T09:39:20.258412Z 0 [Warning] Failed to open optimizer cost constant tables                                                          secshep_mysql |                                                                                                                                                
secshep_mysql | 2021-10-28T09:39:20.273366Z 0 [ERROR] Missing system table mysql.proxies_priv; please run mysql_upgrade to create it                           
secshep_mysql | 2021-10-28T09:39:20.307124Z 0 [ERROR] Native table 'performance_schema'.'cond_instances' has the wrong structure                     
secshep_mysql | 2021-10-28T09:39:20.307151Z 0 [ERROR] Native table 'performance_schema'.'events_waits_current' has the wrong structure    
```

My hypothesis is that initdb sql scripts requires tuning to adapt to recent MySQL docker base image version.
An alternative may be to stuck image to a previous version known to work.

**Comment by ismisepaul** [comment]
Hi @ymartin59 could you please use the Bug template so that we can understand what software you're running so that this can be debugged. 

I've just verified that the instructions in README.md for `docker-compose up` are working without any issue.

The version of MySQL is set here https://github.com/OWASP/SecurityShepherd/blob/8c55d29bfa68ef6680e128ec35ce4638e8e6c271/.env#L4 
so there "should" be no issues when they update their latest image etc.

**Comment by ymartin59** [comment]
I agree my diagnostic/hypothesis was incorrect - even if MySQL errors messages at startup sounds unexpected.

Remain the fact that docker compose sequence does not work as expected (if I understood well): MySQL instance rejects connection and so I get the database setup page.

**Comment by ismisepaul** [comment]
I am not seeing what you are seeing, for me `docker-compose up` is working as expected.

Could you help us understand your setup by using the bug report template. I've added the questions that you'll need to answer to this comment below. But in the future if you find a bug it would be really helpful to use this template instead of "Open a blank issue" so we can get to the root of the problem quickly.

BUG REPORT TEMPLATE

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. chrome, safari]

**Further Information:**
 - `mvn` version [e.g. apache-maven-3.5.0]
 - `docker` version [e.g. Docker version 18.09.0, build 4d60db4]
 - `docker-compose` version [e.g. docker-compose version 1.8.0]
 - `java` version [e.g. 1.8.0_131]

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by ymartin59** [comment]
@ismisepaul I have rebuilt and run on another system: also Debian Testing, Docker 20.10 and docker-compose 1.27 and everything has worked as expected, I was able to login right after.

I have no idea what gets wrong on my first system (which is almost identical in fact) - I have discarded docker images, rebuild three times and always got `Host '172.19.0.4' is not allowed to connect to this MySQL server`

I will go on investigating but definitely it is not a bug in project.

**Comment by ismisepaul** [comment]
@ymartin59 thanks for looking into that and reporting back. I'm glad it is working for you 👍
