### ISSUE TITLE
Add "Password Reset" Function

### ISSUE THREAD

**Issue by markdenihan** [OWASP/SecurityShepherd#82]
Function for admins to reset user passwords

**Comment by markdenihan** [comment]
Pushing this back to V2.3. Not sure how this can be implemented without packaging a mail server into Shepherd. Any ideas?

**Comment by SeanDuggan** [comment]
I know secret questions like "Where were you born" or "What's your favorite pet's name", etc are a horrible practice since all it takes is a little social engineering or some simple guessing.

Would a secret question undermine the security of the Webapp login as much if the answer could be forced to be a certain length and the question, specified by the user?

Maybe this would be too difficult to support as it has a lot of potential for misuse. 

I think email might be the only way.

**Comment by markdenihan** [comment]
I agree. I don't want to compromise the login service with a crappy
solution. I think we could pull this off if we made a web UI for admins to
configure this function with their own mail server, that way shepherd
doesnt have to ship with one.

**Comment by markdenihan** [comment]
Admins can update user passwords. We can revisit adding web-servers later
